version: 2.1
jobs:
  create-database:
    docker:
      - image: cimg/php:7.4
      - image: cimg/mysql:8.0
        environment:
          # MYSQL_ROOT_PASSWORD: fake
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
    steps:
      - checkout
      - run:
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Install MySQL CLI
          command: |
            sudo apt-get update
            sudo apt-get install default-mysql-client
      - run:
          name: Run example queries
          command: |
            mysql -h 127.0.0.1 -u test -ptest -D test --execute="create table example (id bigint(20) unsigned not null auto_increment, description text not null, primary key (id))"
            mysql -h 127.0.0.1 -u test -ptest -D test --execute="insert into example (description) values ('hello'), ('dolly')"
            mysql -h 127.0.0.1 -u test -ptest -D test --execute="select * from example"
workflows:
  version: 2
  create-database-workflow:
    jobs:
      - create-database
